def print_config(config):
    print("\n\n\n\n========= Configuration Info. =========")
    print("\n=======File paths=======")
    print("data_dir: {}".format(config.data_dir))
    print("label_dir: {}".format(config.label_dir))
    print("train_list_file: {}".format(config.train_list_file))
    print("test_list_file: {}".format(config.test_list_file))
    print("log_dir: {}".format(config.log_dir))
    print("model_dir: {}".format(config.model_dir))
    
    print("\n=======Shape model parameters=======")
    print("shape_model_file: {}".format(config.shape_model_file))
    print("eigvec_per: {}".format(config.eigvec_per))
    print("sd: {}".format(config.sd))
    print("landmark_count: {}".format(config.landmark_count))
    print("landmark_unwant: {}".format(config.landmark_unwant))
    
    print("\n=======Experiment parameters=======")
    print("resume: {}".format(config.resume))
    print("box_size (patch size (odd number)): {}".format(config.box_size))
    print("alpha: {}".format(config.alpha))
    print("learning_rate: {}".format(config.learning_rate))
    print("max_steps: {}".format(config.max_steps))
    print("save_interval: {}".format(config.save_interval))
    print("batch_size: {}".format(config.batch_size))
    print("dropout: {}".format(config.dropout))
    print("running on device: {}".format(config.device))
    print("=====================================\n\n\n\n")
    


def print_info(config):
    print("\n\n================================")
    print("Official repository:https://github.com/yuanwei1989/landmark-detection")
    print("Official arxiv: https://arxiv.org/abs/1806.06987v2")
    print("Official paper: https://arxiv.org/pdf/1806.06987.pdf ")
    
    print()
    print()
    print("Writer of this repo: Chaeeun Ryu")
    print("Modifications made compared to the original repo:")
    print("1. Replaced the shape model (i.e., PCA) with the convolutional autoencoder")
    print("2. Wrote code in Pytorch.")
    print()
    print("For detailed information about the library versions, please refer to requirements.txt")
    print("================================)